input.dir = src/BgZ-MSZ-2-0/Validation
output.dir = output/STU3/BgZ-MSZ-2-0/Validation
informationStandard = BgZ MSZ 2.0.x
goal = Validation
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.bgz
package.nictiz.fhir.nl.stu3.bgz = 2.0.3

targets.additional = \
    PatientA/Retrieving-XIS-NoProvenance,\
    PatientA/Serving-XIS-NoProvenance,\
    PatientA/Serving-XIS-CheckContent,\
    PatientB/Retrieving-XIS-NoProvenance,\
    PatientB/Serving-XIS-NoProvenance,\
    PatientB/Serving-XIS-CheckContent,\
    PatientE/Retrieving-XIS-NoProvenance,\
    PatientE/Serving-XIS-NoProvenance,\
    PatientE/Serving-XIS-CheckContent,\
    PatientF/Retrieving-XIS-NoProvenance,\
    PatientF/Serving-XIS-NoProvenance,\
    PatientF/Serving-XIS-CheckContent,\
    PatientG/Retrieving-XIS-NoProvenance,\
    PatientG/Serving-XIS-NoProvenance,\
    PatientG/Serving-XIS-CheckContent