input.dir = src/BgZ-MSZ-1-2-2/Cert
output.dir = output/STU3/BgZ-MSZ-1-2-2/Cert
informationStandard = BgZ MSZ 1.2.2
usecase = MSZ
goal = Cert
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.zib2017

targets.additional = Serving-XIS-CheckContent