input.dir = src/PatientSummary/1.0/euPS
output.dir = output/R4/PatientSummary/1.0/euPS
informationStandard = Patient Summary
goal = Test
serverAlias = nictiz

fhir.version = R4
packages = hl7.fhir.eu.eps
package.hl7.fhir.eu.eps = 1.0.0-ci-build