input.dir = src/eOverdracht-4-2/Cert
output.dir = output/STU3/eOverdracht/4.2/Cert
informationStandard = eOverdracht 4.2
goal = Cert
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.eoverdracht
package.nictiz.fhir.nl.stu3.eoverdracht = 4.2.0-beta.2

roles = Receiving-XIS, Sending-XIS
role.description.Receiving-XIS = XIS of the healthcare provider that is the recipient of the transfer
role.description.Sending-XIS = XIS of the healthcare provider that initiates the transfer

components.dir = src/eOverdracht-4-2/_components
loadresources.exclude = _reference/resources/resources-specific
targets.additional = Sending-XIS-Nictiz-internal, Receiving-XIS-NoDocument, Validation-Sending-XIS-Nictiz-internal, Validation-Receiving-XIS-NoDocument
targets.adminonly = Sending-XIS-Nictiz-internal, Validation-Sending-XIS-Nictiz-internal



