input.dir = src/PatientSummary/1.0/nlPS
output.dir = output/R4/PatientSummary/1.0/nlPS
informationStandard = Patient Summary
goal = Test
serverAlias = nictiz

fhir.version = R4
packages = hl7.fhir.nl.eps
package.hl7.fhir.nl.eps = 1.0.0-ci-build