input.dir = src/BgZ-MSZ-2-0/Cert
output.dir = output/STU3/BgZ-MSZ-2-0/Cert
informationStandard = BgZ MSZ 2.0
usecase = MSZ
goal = Cert
serverAlias = nictiz

fhir.version = STU3

targets.additional = Retrieving-XIS-NoProvenance, Serving-XIS-NoProvenance, Serving-XIS-CheckContent, Validation-Retrieving-XIS-NoProvenance, Validation, Serving-XIS-NoProvenance, Validation-Serving-XIS-CheckContent
target.description.Retrieving-XIS-NoProvenance = Version without _revInclude Provenance (BgZ Metadata) query parameters
target.description.Serving-XIS-NoProvenance = Version without _revInclude Provenance (BgZ Metadata) query parameters
target.description.Serving-XIS-CheckContent =  Version with automated checks on the content of the test scenario
target.description.Validation-Retrieving-XIS-NoProvenance = Version without _revInclude Provenance (BgZ Metadata) query parameters
target.description.Validation-Serving-XIS-NoProvenance = Version without _revInclude Provenance (BgZ Metadata) query parameters
target.description.Validation-Serving-XIS-CheckContent =  Version with automated checks on the content of the test scenario
