input.dir = src/BgZ-MSZ-2-0/Cert
output.dir = output/STU3/BgZ-MSZ-2-0/Cert
informationStandard = BgZ MSZ 2.0
usecase = MSZ
goal = Cert
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.bgz

targets.additional = Retrieving-XIS-NoProvenance,Serving-XIS-NoProvenance,Serving-XIS-CheckContent,Validation-Retrieving-XIS-NoProvenance,Validation-Serving-XIS-NoProvenance,Validation-Serving-XIS-CheckContent

packages = nictiz.fhir.nl.stu3.bgz, nictiz.fhir.nl.stu3.zib2017