input.dir = src/eOverdracht-4-0/Validation
output.dir = output/STU3/eOverdracht/4.0/Validation
informationStandard = eOverdracht 4.0
goal = Validation
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.eoverdracht
package.nictiz.fhir.nl.stu3.eoverdracht = 4.0.0

components.dir = src/eOverdracht-4-0/_components
loadresources.exclude = _reference/resources/resources-specific
targets.additional = \
    PatientXXX_Gaalen-Linder/Sending-XIS-Nictiz-internal,\
    PatientXXX_Gaalen-Linder/Receiving-XIS-NoDocument,\
    PatientXXX_Molog/Sending-XIS-Nictiz-internal,\
    PatientXXX_Molog/Receiving-XIS-NoDocument,\
    PatientXXX_Schaefer/Sending-XIS-Nictiz-internal,\
    PatientXXX_Schaefer/Receiving-XIS-NoDocument,\
    PatientXXX_Wilhelmy-Damste/Sending-XIS-Nictiz-internal,\
    PatientXXX_Wilhelmy-Damste/Receiving-XIS-NoDocument,\
    PatientXXX-TEST-E/Sending-XIS-Nictiz-internal,\
    PatientXXX-TEST-E/Receiving-XIS-NoDocument,\
targets.adminOnly = \
    PatientXXX_Gaalen-Linder/Sending-XIS-Nictiz-internal,\
    PatientXXX_Molog/Sending-XIS-Nictiz-internal,\
    PatientXXX_Schaefer/Sending-XIS-Nictiz-internal,\
    PatientXXX_Wilhelmy-Damste/Sending-XIS-Nictiz-internal,\
    PatientXXX-TEST-E/Sending-XIS-Nictiz-internal