/*
 rule.summary=Create new Task fixture
 rule.description=Create a new Task fixture based on the retreived Task for later use in the TestScript. This is not an actual test, but a step needed for the TestScript infrastructure.
 rule.param.newStatus.required=true
 rule.param.fixtureId.required=true
 rule.param.responseId.required=false
*/

import groovy.xml.XmlUtil;
import groovy.util.slurpersupport.Node$1;
import net.sf.saxon.AugmentedSource
import net.sf.saxon.CollectionURIResolver
import net.sf.saxon.Compile$TracingObjectOutputStream
import net.sf.saxon.Compile
import net.sf.saxon.Configuration
import net.sf.saxon.Controller
import net.sf.saxon.FeatureKeys
import net.sf.saxon.Filter
import net.sf.saxon.IdentityTransformer
import net.sf.saxon.IdentityTransformerHandler
import net.sf.saxon.NonDelegatingURIResolver
import net.sf.saxon.OutputURIResolver
import net.sf.saxon.Platform
import net.sf.saxon.PreparedStylesheet
import net.sf.saxon.Query$1
import net.sf.saxon.Query
import net.sf.saxon.RelativeURIResolver
import net.sf.saxon.SourceResolver
import net.sf.saxon.StandardErrorHandler
import net.sf.saxon.StandardErrorListener
import net.sf.saxon.StandardURIResolver
import net.sf.saxon.TemplatesHandlerImpl$1
import net.sf.saxon.TemplatesHandlerImpl
import net.sf.saxon.Transform
import net.sf.saxon.TransformerFactoryImpl
import net.sf.saxon.TransformerHandlerImpl
import net.sf.saxon.Version
import net.sf.saxon.charcode.ASCIICharacterSet
import net.sf.saxon.charcode.Big5CharacterSet
import net.sf.saxon.charcode.BuggyCharacterSet
import net.sf.saxon.charcode.CharacterSet
import net.sf.saxon.charcode.CharacterSetFactory
import net.sf.saxon.charcode.CP1250CharacterSet
import net.sf.saxon.charcode.CP1251CharacterSet
import net.sf.saxon.charcode.CP1252CharacterSet
import net.sf.saxon.charcode.CP852CharacterSet
import net.sf.saxon.charcode.EucJPCharacterSet
import net.sf.saxon.charcode.EucKRCharacterSet
import net.sf.saxon.charcode.GB2312CharacterSet
import net.sf.saxon.charcode.ISO88591CharacterSet
import net.sf.saxon.charcode.ISO88592CharacterSet
import net.sf.saxon.charcode.ISO88595CharacterSet
import net.sf.saxon.charcode.ISO88597CharacterSet
import net.sf.saxon.charcode.ISO88598CharacterSet
import net.sf.saxon.charcode.ISO88599CharacterSet
import net.sf.saxon.charcode.KOI8RCharacterSet
import net.sf.saxon.charcode.PluggableCharacterSet
import net.sf.saxon.charcode.ShiftJISCharacterSet
import net.sf.saxon.charcode.UnicodeCharacterSet
import net.sf.saxon.charcode.UnknownCharacterSet
import net.sf.saxon.charcode.UTF16
import net.sf.saxon.charcode.XMLCharacterData
import net.sf.saxon.codenorm.Normalizer
import net.sf.saxon.codenorm.NormalizerData
import net.sf.saxon.codenorm.UnicodeData
import net.sf.saxon.codenorm.UnicodeDataGenerator
import net.sf.saxon.codenorm.UnicodeDataParser
import net.sf.saxon.event.Builder
import net.sf.saxon.event.CDATAFilter
import net.sf.saxon.event.CharacterMapExpander
import net.sf.saxon.event.CommentStripper
import net.sf.saxon.event.ComplexContentOutputter
import net.sf.saxon.event.ContentHandlerProxy$ContentHandlerProxyTraceListener
import net.sf.saxon.event.ContentHandlerProxy
import net.sf.saxon.event.ContentHandlerProxyLocator
import net.sf.saxon.event.CopyInformee
import net.sf.saxon.event.CopyNamespaceSensitiveException
import net.sf.saxon.event.DocumentSender
import net.sf.saxon.event.Emitter
import net.sf.saxon.event.EventSource
import net.sf.saxon.event.HTMLEmitter
import net.sf.saxon.event.HTMLIndenter
import net.sf.saxon.event.HTMLTagHashSet
import net.sf.saxon.event.HTMLURIEscaper
import net.sf.saxon.event.IDFilter
import net.sf.saxon.event.ImplicitResultChecker
import net.sf.saxon.event.LocationCopier
import net.sf.saxon.event.LocationProvider
import net.sf.saxon.event.MessageEmitter
import net.sf.saxon.event.MessageWarner
import net.sf.saxon.event.MetaTagAdjuster
import net.sf.saxon.event.NamePoolConverter
import net.sf.saxon.event.NamespaceReducer
import net.sf.saxon.event.NoOpenStartTagException
import net.sf.saxon.event.ParseOptions
import net.sf.saxon.event.PIGrabber
import net.sf.saxon.event.PipelineConfiguration
import net.sf.saxon.event.ProxyReceiver
import net.sf.saxon.event.Receiver
import net.sf.saxon.event.ReceiverOptions
import net.sf.saxon.event.ReceivingContentHandler$1
import net.sf.saxon.event.ReceivingContentHandler$LocalLocator
import net.sf.saxon.event.ReceivingContentHandler
import net.sf.saxon.event.SaxonLocator
import net.sf.saxon.event.SaxonOutputKeys
import net.sf.saxon.event.Sender
import net.sf.saxon.event.SequenceCopier
import net.sf.saxon.event.SequenceOutputter
import net.sf.saxon.event.SequenceReceiver
import net.sf.saxon.event.SequenceWriter
import net.sf.saxon.event.SerializerFactory
import net.sf.saxon.event.Sink
import net.sf.saxon.event.SourceLocationProvider
import net.sf.saxon.event.StandardOutputResolver
import net.sf.saxon.event.StartTagBuffer
import net.sf.saxon.event.Stripper
import net.sf.saxon.event.TeeOutputter
import net.sf.saxon.event.TEXTEmitter
import net.sf.saxon.event.TracingFilter
import net.sf.saxon.event.TransformerReceiver
import net.sf.saxon.event.TreeReceiver
import net.sf.saxon.event.TypeCheckingFilter
import net.sf.saxon.event.UncommittedSerializer$1
import net.sf.saxon.event.UncommittedSerializer$PendingNode
import net.sf.saxon.event.UncommittedSerializer
import net.sf.saxon.event.UnicodeNormalizer
import net.sf.saxon.event.XHTMLEmitter
import net.sf.saxon.event.XHTMLIndenter
import net.sf.saxon.event.XHTMLURIEscaper
import net.sf.saxon.event.XML10ContentChecker
import net.sf.saxon.event.XMLEmitter
import net.sf.saxon.event.XMLIndenter
import net.sf.saxon.event.XQueryEmitter
import net.sf.saxon.evpull.BlockEventIterator
import net.sf.saxon.evpull.BracketedDocumentIterator
import net.sf.saxon.evpull.BracketedElementIterator
import net.sf.saxon.evpull.ComplexContentProcessor
import net.sf.saxon.evpull.Decomposer
import net.sf.saxon.evpull.EmptyEventIterator
import net.sf.saxon.evpull.EndDocumentEvent
import net.sf.saxon.evpull.EndElementEvent
import net.sf.saxon.evpull.EventAnnotationStripper
import net.sf.saxon.evpull.EventIterator
import net.sf.saxon.evpull.EventIteratorOverSequence
import net.sf.saxon.evpull.EventIteratorToReceiver
import net.sf.saxon.evpull.EventMappingFunction
import net.sf.saxon.evpull.EventMappingIterator
import net.sf.saxon.evpull.EventStackIterator
import net.sf.saxon.evpull.EventToStaxBridge$1
import net.sf.saxon.evpull.EventToStaxBridge$2
import net.sf.saxon.evpull.EventToStaxBridge$DummyLocation
import net.sf.saxon.evpull.EventToStaxBridge$SourceStreamLocation
import net.sf.saxon.evpull.EventToStaxBridge
import net.sf.saxon.evpull.NamespaceMaintainer
import net.sf.saxon.evpull.PullEvent
import net.sf.saxon.evpull.PullEventSource
import net.sf.saxon.evpull.PullEventTracer
import net.sf.saxon.evpull.SequenceComposer$SubtreeIterator
import net.sf.saxon.evpull.SequenceComposer
import net.sf.saxon.evpull.SingletonEventIterator
import net.sf.saxon.evpull.StartDocumentEvent
import net.sf.saxon.evpull.StartElementEvent
import net.sf.saxon.evpull.StaxToEventBridge$1
import net.sf.saxon.evpull.StaxToEventBridge$StaxErrorReporter
import net.sf.saxon.evpull.StaxToEventBridge
import net.sf.saxon.evpull.TracingEventIterator
import net.sf.saxon.expr.AppendIterator
import net.sf.saxon.expr.ArithmeticExpression
import net.sf.saxon.expr.ArithmeticExpression10
import net.sf.saxon.expr.Assignation
import net.sf.saxon.expr.AtomicMappingExpression
import net.sf.saxon.expr.AtomicSequenceConverter$1
import net.sf.saxon.expr.AtomicSequenceConverter
import net.sf.saxon.expr.Atomizer$AtomizingFunction
import net.sf.saxon.expr.Atomizer
import net.sf.saxon.expr.AxisAtomizingIterator
import net.sf.saxon.expr.AxisExpression
import net.sf.saxon.expr.BinaryExpression
import net.sf.saxon.expr.Binding
import net.sf.saxon.expr.BindingReference
import net.sf.saxon.expr.BooleanExpression
import net.sf.saxon.expr.BreakInstr
import net.sf.saxon.expr.Calculator$1
import net.sf.saxon.expr.Calculator$AnyDivAny
import net.sf.saxon.expr.Calculator$AnyIdivAny
import net.sf.saxon.expr.Calculator$AnyMinusAny
import net.sf.saxon.expr.Calculator$AnyModAny
import net.sf.saxon.expr.Calculator$AnyPlusAny
import net.sf.saxon.expr.Calculator$AnyTimesAny
import net.sf.saxon.expr.Calculator$DateTimeMinusDateTime
import net.sf.saxon.expr.Calculator$DateTimeMinusDuration
import net.sf.saxon.expr.Calculator$DateTimePlusDuration
import net.sf.saxon.expr.Calculator$DecimalDivDecimal
import net.sf.saxon.expr.Calculator$DecimalIdivDecimal
import net.sf.saxon.expr.Calculator$DecimalMinusDecimal
import net.sf.saxon.expr.Calculator$DecimalModDecimal
import net.sf.saxon.expr.Calculator$DecimalPlusDecimal
import net.sf.saxon.expr.Calculator$DecimalTimesDecimal
import net.sf.saxon.expr.Calculator$DoubleDivDouble
import net.sf.saxon.expr.Calculator$DoubleIdivDouble
import net.sf.saxon.expr.Calculator$DoubleMinusDouble
import net.sf.saxon.expr.Calculator$DoubleModDouble
import net.sf.saxon.expr.Calculator$DoublePlusDouble
import net.sf.saxon.expr.Calculator$DoubleTimesDouble
import net.sf.saxon.expr.Calculator$DurationDivDuration
import net.sf.saxon.expr.Calculator$DurationDivNumeric
import net.sf.saxon.expr.Calculator$DurationMinusDuration
import net.sf.saxon.expr.Calculator$DurationPlusDateTime
import net.sf.saxon.expr.Calculator$DurationPlusDuration
import net.sf.saxon.expr.Calculator$DurationTimesNumeric
import net.sf.saxon.expr.Calculator$FloatDivFloat
import net.sf.saxon.expr.Calculator$FloatIdivFloat
import net.sf.saxon.expr.Calculator$FloatMinusFloat
import net.sf.saxon.expr.Calculator$FloatModFloat
import net.sf.saxon.expr.Calculator$FloatPlusFloat
import net.sf.saxon.expr.Calculator$FloatTimesFloat
import net.sf.saxon.expr.Calculator$IntegerDivInteger
import net.sf.saxon.expr.Calculator$IntegerIdivInteger
import net.sf.saxon.expr.Calculator$IntegerMinusInteger
import net.sf.saxon.expr.Calculator$IntegerModInteger
import net.sf.saxon.expr.Calculator$IntegerPlusInteger
import net.sf.saxon.expr.Calculator$IntegerTimesInteger
import net.sf.saxon.expr.Calculator$NumericTimesDuration
import net.sf.saxon.expr.Calculator
import net.sf.saxon.expr.CardinalityChecker
import net.sf.saxon.expr.CardinalityCheckingIterator
import net.sf.saxon.expr.CastableExpression
import net.sf.saxon.expr.CastExpression
import net.sf.saxon.expr.CodeGeneratorService
import net.sf.saxon.expr.CollationMap
import net.sf.saxon.expr.CompareToIntegerConstant
import net.sf.saxon.expr.ComparisonExpression
import net.sf.saxon.expr.Container
import net.sf.saxon.expr.ContextItemExpression
import net.sf.saxon.expr.ContextMappingFunction
import net.sf.saxon.expr.ContextMappingIterator
import net.sf.saxon.expr.ContinueInstr
import net.sf.saxon.expr.CurrentItemExpression
import net.sf.saxon.expr.DifferenceEnumeration
import net.sf.saxon.expr.EagerLetExpression
import net.sf.saxon.expr.EarlyEvaluationContext
import net.sf.saxon.expr.ErrorExpression
import net.sf.saxon.expr.ErrorIterator
import net.sf.saxon.expr.EvaluableItem
import net.sf.saxon.expr.EveryItemMappingIterator
import net.sf.saxon.expr.Expression
import net.sf.saxon.expr.ExpressionLocation
import net.sf.saxon.expr.ExpressionParser$ForClause
import net.sf.saxon.expr.ExpressionParser$TemporaryContainer
import net.sf.saxon.expr.ExpressionParser
import net.sf.saxon.expr.ExpressionTool
import net.sf.saxon.expr.ExpressionVisitor
import net.sf.saxon.expr.FilterExpression
import net.sf.saxon.expr.FilterIterator$Leading
import net.sf.saxon.expr.FilterIterator$NonNumeric
import net.sf.saxon.expr.FilterIterator
import net.sf.saxon.expr.FirstItemExpression
import net.sf.saxon.expr.ForExpression$EventMappingAction
import net.sf.saxon.expr.ForExpression$MappingAction
import net.sf.saxon.expr.ForExpression
import net.sf.saxon.expr.FunctionCall
import net.sf.saxon.expr.GeneralComparison
import net.sf.saxon.expr.GeneralComparison10
import net.sf.saxon.expr.IdentityComparison
import net.sf.saxon.expr.InstanceOfExpression
import net.sf.saxon.expr.IntegerRangeTest
import net.sf.saxon.expr.IntersectionEnumeration
import net.sf.saxon.expr.IsLastExpression
import net.sf.saxon.expr.ItemChecker$1
import net.sf.saxon.expr.ItemChecker$ItemCheckMappingFunction
import net.sf.saxon.expr.ItemChecker
import net.sf.saxon.expr.ItemMappingFunction
import net.sf.saxon.expr.ItemMappingIterator
import net.sf.saxon.expr.IterateInstr
import net.sf.saxon.expr.JPConverter$FromBigDecimal
import net.sf.saxon.expr.JPConverter$FromBigInteger
import net.sf.saxon.expr.JPConverter$FromBoolean
import net.sf.saxon.expr.JPConverter$FromBooleanArray
import net.sf.saxon.expr.JPConverter$FromByte
import net.sf.saxon.expr.JPConverter$FromByteArray
import net.sf.saxon.expr.JPConverter$FromCharacter
import net.sf.saxon.expr.JPConverter$FromCharArray
import net.sf.saxon.expr.JPConverter$FromCollection
import net.sf.saxon.expr.JPConverter$FromDate
import net.sf.saxon.expr.JPConverter$FromDouble
import net.sf.saxon.expr.JPConverter$FromDoubleArray
import net.sf.saxon.expr.JPConverter$FromFloat
import net.sf.saxon.expr.JPConverter$FromFloatArray
import net.sf.saxon.expr.JPConverter$FromInt
import net.sf.saxon.expr.JPConverter$FromIntArray
import net.sf.saxon.expr.JPConverter$FromLong
import net.sf.saxon.expr.JPConverter$FromLongArray
import net.sf.saxon.expr.JPConverter$FromObjectArray
import net.sf.saxon.expr.JPConverter$FromQName
import net.sf.saxon.expr.JPConverter$FromSequenceIterator
import net.sf.saxon.expr.JPConverter$FromShort
import net.sf.saxon.expr.JPConverter$FromShortArray
import net.sf.saxon.expr.JPConverter$FromSource
import net.sf.saxon.expr.JPConverter$FromString
import net.sf.saxon.expr.JPConverter$FromURI
import net.sf.saxon.expr.JPConverter$FromValueRepresentation
import net.sf.saxon.expr.JPConverter$WrapExternalObject
import net.sf.saxon.expr.JPConverter
import net.sf.saxon.expr.LastItemExpression
import net.sf.saxon.expr.LastPositionFinder
import net.sf.saxon.expr.LazyExpression
import net.sf.saxon.expr.LetExpression
import net.sf.saxon.expr.Literal
import net.sf.saxon.expr.LocalVariableReference
import net.sf.saxon.expr.MappingFunction
import net.sf.saxon.expr.MappingIterator
import net.sf.saxon.expr.MonoIterator
import net.sf.saxon.expr.MultiIterator
import net.sf.saxon.expr.Negatable
import net.sf.saxon.expr.NegateExpression
import net.sf.saxon.expr.NumericPromoter$1
import net.sf.saxon.expr.NumericPromoter
import net.sf.saxon.expr.Optimizer
import net.sf.saxon.expr.PairIterator
import net.sf.saxon.expr.ParentNodeExpression
import net.sf.saxon.expr.PathExpression
import net.sf.saxon.expr.PathMap$1
import net.sf.saxon.expr.PathMap$PathMapArc
import net.sf.saxon.expr.PathMap$PathMapNode
import net.sf.saxon.expr.PathMap$PathMapNodeSet
import net.sf.saxon.expr.PathMap$PathMapRoot
import net.sf.saxon.expr.PathMap
import net.sf.saxon.expr.PatternMatchExpression
import net.sf.saxon.expr.PendingUpdateList
import net.sf.saxon.expr.PJConverter$AnyURIValueToURI
import net.sf.saxon.expr.PJConverter$AnyURIValueToURL
import net.sf.saxon.expr.PJConverter$Atomic
import net.sf.saxon.expr.PJConverter$BooleanValueToBoolean
import net.sf.saxon.expr.PJConverter$CalendarValueToCalendar
import net.sf.saxon.expr.PJConverter$CalendarValueToDate
import net.sf.saxon.expr.PJConverter$General
import net.sf.saxon.expr.PJConverter$Identity
import net.sf.saxon.expr.PJConverter$IntegerValueToBigInteger
import net.sf.saxon.expr.PJConverter$IntegerValueToByte
import net.sf.saxon.expr.PJConverter$IntegerValueToChar
import net.sf.saxon.expr.PJConverter$IntegerValueToInt
import net.sf.saxon.expr.PJConverter$IntegerValueToLong
import net.sf.saxon.expr.PJConverter$IntegerValueToShort
import net.sf.saxon.expr.PJConverter$NumericValueToBigDecimal
import net.sf.saxon.expr.PJConverter$NumericValueToDouble
import net.sf.saxon.expr.PJConverter$NumericValueToFloat
import net.sf.saxon.expr.PJConverter$QualifiedNameValueToQName
import net.sf.saxon.expr.PJConverter$StringValueToChar
import net.sf.saxon.expr.PJConverter$StringValueToString
import net.sf.saxon.expr.PJConverter$ToArray
import net.sf.saxon.expr.PJConverter$ToCollection
import net.sf.saxon.expr.PJConverter$ToNull
import net.sf.saxon.expr.PJConverter$ToSequenceExtent
import net.sf.saxon.expr.PJConverter$ToSequenceIterator
import net.sf.saxon.expr.PJConverter$UnwrapExternalObject
import net.sf.saxon.expr.PJConverter
import net.sf.saxon.expr.PositionVariable
import net.sf.saxon.expr.PromotionOffer
import net.sf.saxon.expr.QuantifiedExpression
import net.sf.saxon.expr.RangeExpression
import net.sf.saxon.expr.RangeIterator
import net.sf.saxon.expr.ReverseRangeIterator
import net.sf.saxon.expr.ReversibleIterator
import net.sf.saxon.expr.RoleLocator
import net.sf.saxon.expr.RootExpression
import net.sf.saxon.expr.SequenceIterable
import net.sf.saxon.expr.SimpleExpression
import net.sf.saxon.expr.SingleNodeExpression
import net.sf.saxon.expr.SingletonAtomizer
import net.sf.saxon.expr.SingletonComparison
import net.sf.saxon.expr.SlashExpression$1
import net.sf.saxon.expr.SlashExpression$2
import net.sf.saxon.expr.SlashExpression
import net.sf.saxon.expr.StackFrame
import net.sf.saxon.expr.StatefulMappingFunction
import net.sf.saxon.expr.StaticContext
import net.sf.saxon.expr.StaticProperty
import net.sf.saxon.expr.StringLiteral
import net.sf.saxon.expr.StringTokenIterator
import net.sf.saxon.expr.SubsequenceIterator
import net.sf.saxon.expr.SuppliedParameterReference
import net.sf.saxon.expr.TailCallLoop
import net.sf.saxon.expr.TailExpression
import net.sf.saxon.expr.TailIterator
import net.sf.saxon.expr.Token
import net.sf.saxon.expr.Tokenizer
import net.sf.saxon.expr.TreatExpression
import net.sf.saxon.expr.TypeChecker
import net.sf.saxon.expr.UnaryExpression
import net.sf.saxon.expr.UnionEnumeration
import net.sf.saxon.expr.UntypedAtomicConverter$1
import net.sf.saxon.expr.UntypedAtomicConverter
import net.sf.saxon.expr.UserFunctionCall
import net.sf.saxon.expr.ValueComparison
import net.sf.saxon.expr.ValueTailIterator
import net.sf.saxon.expr.VariableDeclaration
import net.sf.saxon.expr.VariableReference
import net.sf.saxon.expr.VennExpression
import net.sf.saxon.expr.XPathContext
import net.sf.saxon.expr.XPathContextMajor
import net.sf.saxon.expr.XPathContextMinor
import net.sf.saxon.exslt.Common
import net.sf.saxon.exslt.Date
import net.sf.saxon.exslt.Math
import net.sf.saxon.exslt.Random$RandomIterator
import net.sf.saxon.exslt.Random
import net.sf.saxon.exslt.Sets
import net.sf.saxon.functions.Adjust
import net.sf.saxon.functions.Aggregate
import net.sf.saxon.functions.Available
import net.sf.saxon.functions.BaseURI
import net.sf.saxon.functions.BooleanFn
import net.sf.saxon.functions.CodepointEqual
import net.sf.saxon.functions.CodepointsToString
import net.sf.saxon.functions.CollatingFunction
import net.sf.saxon.functions.Collection$1
import net.sf.saxon.functions.Collection
import net.sf.saxon.functions.Compare
import net.sf.saxon.functions.CompileTimeFunction
import net.sf.saxon.functions.Component
import net.sf.saxon.functions.Concat
import net.sf.saxon.functions.ConstructorFunctionLibrary
import net.sf.saxon.functions.Contains
import net.sf.saxon.functions.Current
import net.sf.saxon.functions.CurrentDateTime
import net.sf.saxon.functions.CurrentGroup
import net.sf.saxon.functions.Data
import net.sf.saxon.functions.DateTimeConstructor
import net.sf.saxon.functions.DeepEqual
import net.sf.saxon.functions.DefaultCollation
import net.sf.saxon.functions.DistinctValues$DistinctIterator
import net.sf.saxon.functions.DistinctValues
import net.sf.saxon.functions.Doc
import net.sf.saxon.functions.DocAvailable$1
import net.sf.saxon.functions.DocAvailable
import net.sf.saxon.functions.Document$DocumentMappingFunction
import net.sf.saxon.functions.Document
import net.sf.saxon.functions.Error
import net.sf.saxon.functions.EscapeURI
import net.sf.saxon.functions.Evaluate$PreparedExpression
import net.sf.saxon.functions.Evaluate
import net.sf.saxon.functions.ExecutableFunctionLibrary
import net.sf.saxon.functions.Existence
import net.sf.saxon.functions.ExtensionFunctionCall$ConfigurationCheckingFunction
import net.sf.saxon.functions.ExtensionFunctionCall$MethodRepresentation
import net.sf.saxon.functions.ExtensionFunctionCall
import net.sf.saxon.functions.ExtensionFunctionFactory
import net.sf.saxon.functions.Extensions$1
import net.sf.saxon.functions.Extensions$2
import net.sf.saxon.functions.Extensions
import net.sf.saxon.functions.ForceCase
import net.sf.saxon.functions.FormatDate
import net.sf.saxon.functions.FormatNumber$SubPicture
import net.sf.saxon.functions.FormatNumber
import net.sf.saxon.functions.FunctionLibrary
import net.sf.saxon.functions.FunctionLibraryList
import net.sf.saxon.functions.Id$1
import net.sf.saxon.functions.Id$IdMappingFunction
import net.sf.saxon.functions.Id
import net.sf.saxon.functions.Idref$1
import net.sf.saxon.functions.Idref$IdrefMappingFunction
import net.sf.saxon.functions.Idref
import net.sf.saxon.functions.IndexOf$IndexIterator
import net.sf.saxon.functions.IndexOf
import net.sf.saxon.functions.InScopePrefixes$1
import net.sf.saxon.functions.InScopePrefixes
import net.sf.saxon.functions.Insert$InsertIterator
import net.sf.saxon.functions.Insert
import net.sf.saxon.functions.IsWholeNumber
import net.sf.saxon.functions.ItemAt
import net.sf.saxon.functions.JavaExtensionFunctionFactory
import net.sf.saxon.functions.JavaExtensionLibrary$UnresolvedExtensionFunction
import net.sf.saxon.functions.JavaExtensionLibrary
import net.sf.saxon.functions.KeyFn$1
import net.sf.saxon.functions.KeyFn$SubtreeFilter
import net.sf.saxon.functions.KeyFn
import net.sf.saxon.functions.Lang
import net.sf.saxon.functions.Last
import net.sf.saxon.functions.Matches
import net.sf.saxon.functions.Minimax
import net.sf.saxon.functions.NamePart
import net.sf.saxon.functions.NamespaceForPrefix
import net.sf.saxon.functions.Nilled
import net.sf.saxon.functions.NormalizeSpace
import net.sf.saxon.functions.NormalizeUnicode
import net.sf.saxon.functions.NumberFn
import net.sf.saxon.functions.Parse
import net.sf.saxon.functions.Position
import net.sf.saxon.functions.Put
import net.sf.saxon.functions.QNameFn
import net.sf.saxon.functions.RegexGroup
import net.sf.saxon.functions.Remove$RemoveIterator
import net.sf.saxon.functions.Remove
import net.sf.saxon.functions.Replace
import net.sf.saxon.functions.ResolveQName
import net.sf.saxon.functions.ResolveURI
import net.sf.saxon.functions.Reverse
import net.sf.saxon.functions.Root
import net.sf.saxon.functions.Rounding
import net.sf.saxon.functions.Serialize
import net.sf.saxon.functions.StandardCollectionURIResolver$1
import net.sf.saxon.functions.StandardCollectionURIResolver$2
import net.sf.saxon.functions.StandardCollectionURIResolver$3
import net.sf.saxon.functions.StandardCollectionURIResolver$FileExpander
import net.sf.saxon.functions.StandardCollectionURIResolver
import net.sf.saxon.functions.StandardFunction$Entry
import net.sf.saxon.functions.StandardFunction
import net.sf.saxon.functions.StaticBaseURI
import net.sf.saxon.functions.StringFn
import net.sf.saxon.functions.StringJoin
import net.sf.saxon.functions.StringLength
import net.sf.saxon.functions.StringToCodepoints
import net.sf.saxon.functions.Subsequence
import net.sf.saxon.functions.Substring
import net.sf.saxon.functions.SystemFunction
import net.sf.saxon.functions.SystemFunctionLibrary
import net.sf.saxon.functions.SystemProperty
import net.sf.saxon.functions.Tokenize
import net.sf.saxon.functions.Trace$TracingIterator
import net.sf.saxon.functions.Trace
import net.sf.saxon.functions.Translate
import net.sf.saxon.functions.TreatFn
import net.sf.saxon.functions.Unordered
import net.sf.saxon.functions.UnparsedEntity
import net.sf.saxon.functions.UnparsedText
import net.sf.saxon.functions.URIQueryParameters$RegexFilter
import net.sf.saxon.functions.URIQueryParameters
import net.sf.saxon.functions.VendorFunctionLibrary
import net.sf.saxon.functions.XSLTFunction
import net.sf.saxon.instruct.AnalyzeString$AnalyzeMappingFunction
import net.sf.saxon.instruct.AnalyzeString
import net.sf.saxon.instruct.ApplyImports
import net.sf.saxon.instruct.ApplyTemplates$ApplyTemplatesPackage
import net.sf.saxon.instruct.ApplyTemplates
import net.sf.saxon.instruct.Assign
import net.sf.saxon.instruct.AttributeCreator
import net.sf.saxon.instruct.AttributeSet
import net.sf.saxon.instruct.Bindery$1
import net.sf.saxon.instruct.Bindery$2
import net.sf.saxon.instruct.Bindery$3
import net.sf.saxon.instruct.Bindery
import net.sf.saxon.instruct.Block
import net.sf.saxon.instruct.BlockIterator
import net.sf.saxon.instruct.CallTemplate$CallTemplatePackage
import net.sf.saxon.instruct.CallTemplate
import net.sf.saxon.instruct.Choose
import net.sf.saxon.instruct.Comment
import net.sf.saxon.instruct.ComputedAttribute
import net.sf.saxon.instruct.ComputedElement
import net.sf.saxon.instruct.Copy
import net.sf.saxon.instruct.CopyOf$1
import net.sf.saxon.instruct.CopyOf$2
import net.sf.saxon.instruct.CopyOf
import net.sf.saxon.instruct.Debugger
import net.sf.saxon.instruct.Doctype
import net.sf.saxon.instruct.DocumentInstr
import net.sf.saxon.instruct.DummyNamespaceResolver
import net.sf.saxon.instruct.ElementCreator
import net.sf.saxon.instruct.Executable
import net.sf.saxon.instruct.FixedAttribute
import net.sf.saxon.instruct.FixedElement
import net.sf.saxon.instruct.ForEach
import net.sf.saxon.instruct.ForEachGroup
import net.sf.saxon.instruct.GeneralVariable
import net.sf.saxon.instruct.GlobalParam
import net.sf.saxon.instruct.GlobalParameterSet
import net.sf.saxon.instruct.GlobalVariable
import net.sf.saxon.instruct.Instruction
import net.sf.saxon.instruct.InstructionDetails
import net.sf.saxon.instruct.LocalParam
import net.sf.saxon.instruct.LocalVariable
import net.sf.saxon.instruct.LocationMap
import net.sf.saxon.instruct.Message$AttributeMasker
import net.sf.saxon.instruct.Message
import net.sf.saxon.instruct.Namespace
import net.sf.saxon.instruct.NextMatch$NextMatchPackage
import net.sf.saxon.instruct.NextMatch
import net.sf.saxon.instruct.NumberInstruction
import net.sf.saxon.instruct.ParameterSet
import net.sf.saxon.instruct.ParentNodeConstructor
import net.sf.saxon.instruct.Procedure
import net.sf.saxon.instruct.ProcessingInstruction
import net.sf.saxon.instruct.QuerySimpleContentConstructor
import net.sf.saxon.instruct.ResultDocument
import net.sf.saxon.instruct.SavedNamespaceContext
import net.sf.saxon.instruct.SimpleContentConstructor
import net.sf.saxon.instruct.SimpleNodeConstructor
import net.sf.saxon.instruct.SlotManager
import net.sf.saxon.instruct.TailCall
import net.sf.saxon.instruct.TailCallReturner
import net.sf.saxon.instruct.Template
import net.sf.saxon.instruct.TerminationException
import net.sf.saxon.instruct.TraceExpression
import net.sf.saxon.instruct.TraceInstruction
import net.sf.saxon.instruct.TraceWrapper
import net.sf.saxon.instruct.UseAttributeSets
import net.sf.saxon.instruct.UserFunction
import net.sf.saxon.instruct.UserFunctionParameter
import net.sf.saxon.instruct.ValueOf
import net.sf.saxon.instruct.While
import net.sf.saxon.instruct.WithParam
import net.sf.saxon.java.JavaCollationFactory
import net.sf.saxon.java.JavaPlatform
import net.sf.saxon.java.JDK14RegexTranslator$Subtraction
import net.sf.saxon.java.JDK14RegexTranslator$Union
import net.sf.saxon.java.JDK14RegexTranslator
import net.sf.saxon.java.JDK15RegexTranslator$BackReference
import net.sf.saxon.java.JDK15RegexTranslator$CharClass
import net.sf.saxon.java.JDK15RegexTranslator$CharRange
import net.sf.saxon.java.JDK15RegexTranslator$Complement
import net.sf.saxon.java.JDK15RegexTranslator$Empty
import net.sf.saxon.java.JDK15RegexTranslator$Property
import net.sf.saxon.java.JDK15RegexTranslator$SimpleCharClass
import net.sf.saxon.java.JDK15RegexTranslator$SingleChar
import net.sf.saxon.java.JDK15RegexTranslator$Subtraction
import net.sf.saxon.java.JDK15RegexTranslator$Union
import net.sf.saxon.java.JDK15RegexTranslator
import net.sf.saxon.java.JRegexIterator
import net.sf.saxon.java.JRegularExpression
import net.sf.saxon.java.JTokenIterator
import net.sf.saxon.number.AbstractNumberer
import net.sf.saxon.number.Alphanumeric
import net.sf.saxon.number.NamedTimeZone
import net.sf.saxon.number.Numberer
import net.sf.saxon.number.Numberer_da
import net.sf.saxon.number.Numberer_de
import net.sf.saxon.number.Numberer_en
import net.sf.saxon.number.Numberer_fr
import net.sf.saxon.number.Numberer_frBE
import net.sf.saxon.number.Numberer_it
import net.sf.saxon.number.Numberer_nl
import net.sf.saxon.number.Numberer_nlBE
import net.sf.saxon.number.Numberer_sv
import net.sf.saxon.number.NumberFormatter
import net.sf.saxon.om.AllElementStripper
import net.sf.saxon.om.ArrayIterator
import net.sf.saxon.om.AttributeCollection
import net.sf.saxon.om.AttributeCollectionImpl
import net.sf.saxon.om.Axis
import net.sf.saxon.om.AxisIterator
import net.sf.saxon.om.AxisIteratorImpl
import net.sf.saxon.om.DocumentInfo
import net.sf.saxon.om.DocumentNumberAllocator
import net.sf.saxon.om.DocumentPool
import net.sf.saxon.om.EmptyIterator
import net.sf.saxon.om.EmptyNamespaceDeclarationList
import net.sf.saxon.om.ExternalObjectModel
import net.sf.saxon.om.FastStringBuffer
import net.sf.saxon.om.FingerprintedNode
import net.sf.saxon.om.GroundedIterator
import net.sf.saxon.om.GroundedValue
import net.sf.saxon.om.InscopeNamespaceResolver$1
import net.sf.saxon.om.InscopeNamespaceResolver
import net.sf.saxon.om.Item
import net.sf.saxon.om.ListIterator
import net.sf.saxon.om.LookaheadIterator
import net.sf.saxon.om.MutableNodeInfo
import net.sf.saxon.om.Name10Checker
import net.sf.saxon.om.Name11Checker
import net.sf.saxon.om.NameChecker
import net.sf.saxon.om.NamePool$NameEntry
import net.sf.saxon.om.NamePool$NamePoolLimitException
import net.sf.saxon.om.NamePool
import net.sf.saxon.om.NamespaceCodeIterator
import net.sf.saxon.om.NamespaceConstant
import net.sf.saxon.om.NamespaceDeclarations
import net.sf.saxon.om.NamespaceDeclarationsImpl
import net.sf.saxon.om.NamespaceException
import net.sf.saxon.om.NamespaceIterator$NamespaceNodeImpl
import net.sf.saxon.om.NamespaceIterator
import net.sf.saxon.om.NamespaceResolver
import net.sf.saxon.om.NamespaceResolverAsDeclarations
import net.sf.saxon.om.NamespaceResolverForElements
import net.sf.saxon.om.Navigator$AncestorEnumeration
import net.sf.saxon.om.Navigator$AxisFilter
import net.sf.saxon.om.Navigator$BaseEnumeration
import net.sf.saxon.om.Navigator$DescendantEnumeration
import net.sf.saxon.om.Navigator$FollowingEnumeration
import net.sf.saxon.om.Navigator$PrecedingEnumeration
import net.sf.saxon.om.Navigator
import net.sf.saxon.om.NodeArrayIterator
import net.sf.saxon.om.NodeInfo
import net.sf.saxon.om.NodeListIterator
import net.sf.saxon.om.Orphan
import net.sf.saxon.om.PrefixNormalizer
import net.sf.saxon.om.PrependIterator
import net.sf.saxon.om.ProcInstParser
import net.sf.saxon.om.QNameException
import net.sf.saxon.om.ReverseArrayIterator
import net.sf.saxon.om.ReverseNodeArrayIterator
import net.sf.saxon.om.SequenceIterator
import net.sf.saxon.om.SiblingCountingNode
import net.sf.saxon.om.SingleNodeIterator
import net.sf.saxon.om.SingletonIterator
import net.sf.saxon.om.StandardNames
import net.sf.saxon.om.StrippedDocument
import net.sf.saxon.om.StrippedNode$StrippingIterator
import net.sf.saxon.om.StrippedNode$WrappingIterator
import net.sf.saxon.om.StrippedNode
import net.sf.saxon.om.StructuredQName
import net.sf.saxon.om.UnfailingIterator
import net.sf.saxon.om.Validation
import net.sf.saxon.om.ValueRepresentation
import net.sf.saxon.om.VirtualCopy$VirtualCopier
import net.sf.saxon.om.VirtualCopy
import net.sf.saxon.om.VirtualDocumentCopy
import net.sf.saxon.om.VirtualNode
import net.sf.saxon.om.VirtualUntypedCopy$VirtualUntypedCopier
import net.sf.saxon.om.VirtualUntypedCopy
import net.sf.saxon.pattern.AnyChildNodePattern
import net.sf.saxon.pattern.AnyNodeTest
import net.sf.saxon.pattern.CombinedNodeTest
import net.sf.saxon.pattern.ContentTypeTest
import net.sf.saxon.pattern.DocumentNodeTest
import net.sf.saxon.pattern.EmptySequenceTest
import net.sf.saxon.pattern.IDPattern
import net.sf.saxon.pattern.IdrefTest$1
import net.sf.saxon.pattern.IdrefTest$2
import net.sf.saxon.pattern.IdrefTest
import net.sf.saxon.pattern.KeyPattern
import net.sf.saxon.pattern.LocalNameTest
import net.sf.saxon.pattern.LocationPathPattern
import net.sf.saxon.pattern.NamespaceTest
import net.sf.saxon.pattern.NameTest
import net.sf.saxon.pattern.NodeKindTest
import net.sf.saxon.pattern.NodeTest
import net.sf.saxon.pattern.NodeTestPattern
import net.sf.saxon.pattern.Pattern$1
import net.sf.saxon.pattern.Pattern$2
import net.sf.saxon.pattern.Pattern$3
import net.sf.saxon.pattern.Pattern$4
import net.sf.saxon.pattern.Pattern$5
import net.sf.saxon.pattern.Pattern
import net.sf.saxon.pattern.PatternFinder
import net.sf.saxon.pattern.PatternSponsor
import net.sf.saxon.pattern.SubstitutionGroupTest
import net.sf.saxon.pattern.UnionPattern
import net.sf.saxon.pull.DocumentEventIgnorer
import net.sf.saxon.pull.ElementNameTracker
import net.sf.saxon.pull.NamespaceContextImpl
import net.sf.saxon.pull.PullConsumer
import net.sf.saxon.pull.PullFilter
import net.sf.saxon.pull.PullFromIterator
import net.sf.saxon.pull.PullNamespaceReducer
import net.sf.saxon.pull.PullProvider
import net.sf.saxon.pull.PullPushCopier
import net.sf.saxon.pull.PullPushTee
import net.sf.saxon.pull.PullSource
import net.sf.saxon.pull.PullToStax$SourceStreamLocation
import net.sf.saxon.pull.PullToStax
import net.sf.saxon.pull.PullTracer
import net.sf.saxon.pull.StaxBridge$1
import net.sf.saxon.pull.StaxBridge$StaxAttributes
import net.sf.saxon.pull.StaxBridge$StaxErrorReporter
import net.sf.saxon.pull.StaxBridge$StaxNamespaces
import net.sf.saxon.pull.StaxBridge
import net.sf.saxon.pull.TreeWalker
import net.sf.saxon.pull.UnconstructedDocument
import net.sf.saxon.pull.UnconstructedElement
import net.sf.saxon.pull.UnconstructedParent
import net.sf.saxon.pull.UnparsedEntity
import net.sf.saxon.pull.VirtualTreeWalker
import net.sf.saxon.query.Declaration
import net.sf.saxon.query.DynamicQueryContext
import net.sf.saxon.query.GlobalVariableDefinition
import net.sf.saxon.query.ImportedFunctionLibrary
import net.sf.saxon.query.ModuleURIResolver
import net.sf.saxon.query.QueryModule$1
import net.sf.saxon.query.QueryModule$ActiveNamespace
import net.sf.saxon.query.QueryModule
import net.sf.saxon.query.QueryParser$1
import net.sf.saxon.query.QueryParser$AttributeDetails
import net.sf.saxon.query.QueryParser$Import
import net.sf.saxon.query.QueryParser$LetClause
import net.sf.saxon.query.QueryParser$SortSpec
import net.sf.saxon.query.QueryParser
import net.sf.saxon.query.QueryReader
import net.sf.saxon.query.QueryResult
import net.sf.saxon.query.SequenceWrapper
import net.sf.saxon.query.StandardModuleURIResolver
import net.sf.saxon.query.StaticQueryContext
import net.sf.saxon.query.UnboundFunctionLibrary
import net.sf.saxon.query.UndeclaredVariable
import net.sf.saxon.query.UpdateAgent
import net.sf.saxon.query.XQueryExpression$ErrorReportingIterator
import net.sf.saxon.query.XQueryExpression
import net.sf.saxon.query.XQueryFunction
import net.sf.saxon.query.XQueryFunctionBinder
import net.sf.saxon.query.XQueryFunctionLibrary
import net.sf.saxon.regex.CaseVariants
import net.sf.saxon.regex.RegexData
import net.sf.saxon.regex.RegexIterator
import net.sf.saxon.regex.RegexSyntaxException
import net.sf.saxon.regex.RegexTranslator$Range
import net.sf.saxon.regex.RegexTranslator
import net.sf.saxon.regex.RegularExpression
import net.sf.saxon.regex.SurrogateRegexTranslator$BackReference
import net.sf.saxon.regex.SurrogateRegexTranslator$CharClass
import net.sf.saxon.regex.SurrogateRegexTranslator$CharRange
import net.sf.saxon.regex.SurrogateRegexTranslator$Complement
import net.sf.saxon.regex.SurrogateRegexTranslator$Dot
import net.sf.saxon.regex.SurrogateRegexTranslator$Empty
import net.sf.saxon.regex.SurrogateRegexTranslator$Property
import net.sf.saxon.regex.SurrogateRegexTranslator$SimpleCharClass
import net.sf.saxon.regex.SurrogateRegexTranslator$SingleChar
import net.sf.saxon.regex.SurrogateRegexTranslator$WideSingleChar
import net.sf.saxon.regex.SurrogateRegexTranslator
import net.sf.saxon.sort.AlphanumericCollator
import net.sf.saxon.sort.AtomicComparer
import net.sf.saxon.sort.AtomicSortComparer
import net.sf.saxon.sort.CalendarValueComparer
import net.sf.saxon.sort.CodepointCollatingComparer
import net.sf.saxon.sort.CodepointCollator
import net.sf.saxon.sort.CollatingAtomicComparer
import net.sf.saxon.sort.CollationURIResolver
import net.sf.saxon.sort.ComparableAtomicValueComparer
import net.sf.saxon.sort.ComparisonKey
import net.sf.saxon.sort.ConditionalSorter
import net.sf.saxon.sort.DecimalSortComparer
import net.sf.saxon.sort.DescendingComparer
import net.sf.saxon.sort.DocumentOrderIterator
import net.sf.saxon.sort.DocumentSorter
import net.sf.saxon.sort.DoubleSortComparer
import net.sf.saxon.sort.EmptyGreatestComparer
import net.sf.saxon.sort.EmptyIntIterator
import net.sf.saxon.sort.EqualityComparer
import net.sf.saxon.sort.GenericAtomicComparer
import net.sf.saxon.sort.GenericSorter
import net.sf.saxon.sort.GlobalOrderComparer
import net.sf.saxon.sort.GroupAdjacentIterator
import net.sf.saxon.sort.GroupByIterator
import net.sf.saxon.sort.GroupEndingIterator
import net.sf.saxon.sort.GroupIterator
import net.sf.saxon.sort.GroupStartingIterator
import net.sf.saxon.sort.IntArraySet$IntArraySetIterator
import net.sf.saxon.sort.IntArraySet
import net.sf.saxon.sort.IntHashMap$IntHashMapKeyIterator
import net.sf.saxon.sort.IntHashMap$IntHashMapValueIterator
import net.sf.saxon.sort.IntHashMap$IntHashMapValueIteratorOLD
import net.sf.saxon.sort.IntHashMap
import net.sf.saxon.sort.IntHashSet$IntHashSetIterator
import net.sf.saxon.sort.IntHashSet
import net.sf.saxon.sort.IntIterator
import net.sf.saxon.sort.IntRangeSet$IntRangeSetIterator
import net.sf.saxon.sort.IntRangeSet
import net.sf.saxon.sort.IntSet
import net.sf.saxon.sort.IntToIntArrayMap$KeyIterator
import net.sf.saxon.sort.IntToIntArrayMap
import net.sf.saxon.sort.IntToIntHashMap$IntToIntHashMapKeyIterator
import net.sf.saxon.sort.IntToIntHashMap
import net.sf.saxon.sort.IntToIntMap
import net.sf.saxon.sort.LocalOrderComparer
import net.sf.saxon.sort.LowercaseFirstCollator
import net.sf.saxon.sort.LRUCache$1
import net.sf.saxon.sort.LRUCache
import net.sf.saxon.sort.NamedCollation
import net.sf.saxon.sort.NodeOrderComparer
import net.sf.saxon.sort.NumericComparer
import net.sf.saxon.sort.RuleBasedSubstringMatcher
import net.sf.saxon.sort.Sortable
import net.sf.saxon.sort.SortedGroupIterator
import net.sf.saxon.sort.SortedIterator
import net.sf.saxon.sort.SortedTupleIterator
import net.sf.saxon.sort.SortExpression
import net.sf.saxon.sort.SortKeyDefinition
import net.sf.saxon.sort.SortKeyEvaluator
import net.sf.saxon.sort.StandardCollationURIResolver
import net.sf.saxon.sort.StringCollator
import net.sf.saxon.sort.SubstringMatcher
import net.sf.saxon.sort.TerminatedIntIterator
import net.sf.saxon.sort.TextComparer
import net.sf.saxon.sort.TupleExpression
import net.sf.saxon.sort.TupleSorter$TupleUnwrapper
import net.sf.saxon.sort.TupleSorter
import net.sf.saxon.sort.UppercaseFirstCollator
import net.sf.saxon.style.AbsentExtensionElement
import net.sf.saxon.style.AttributeValueTemplate
import net.sf.saxon.style.DataElement
import net.sf.saxon.style.ExpressionContext
import net.sf.saxon.style.ExtensionElementFactory
import net.sf.saxon.style.ExtensionInstruction
import net.sf.saxon.style.LiteralResultElement
import net.sf.saxon.style.SaxonAssign
import net.sf.saxon.style.SaxonBreak
import net.sf.saxon.style.SaxonCallTemplate
import net.sf.saxon.style.SaxonCollation
import net.sf.saxon.style.SaxonContinue
import net.sf.saxon.style.SaxonDoctype
import net.sf.saxon.style.SaxonEntityRef
import net.sf.saxon.style.SaxonFinally
import net.sf.saxon.style.SaxonImportQuery
import net.sf.saxon.style.SaxonIterate
import net.sf.saxon.style.SaxonScript
import net.sf.saxon.style.SaxonWhile
import net.sf.saxon.style.StyleElement
import net.sf.saxon.style.StyleNodeFactory
import net.sf.saxon.style.StylesheetFunctionLibrary
import net.sf.saxon.style.StylesheetProcedure
import net.sf.saxon.style.StylesheetStripper
import net.sf.saxon.style.UseWhenFilter$1
import net.sf.saxon.style.UseWhenFilter$URIPreventer
import net.sf.saxon.style.UseWhenFilter
import net.sf.saxon.style.UseWhenStaticContext
import net.sf.saxon.style.XSLAnalyzeString
import net.sf.saxon.style.XSLApplyImports
import net.sf.saxon.style.XSLApplyTemplates
import net.sf.saxon.style.XSLAttribute
import net.sf.saxon.style.XSLAttributeSet
import net.sf.saxon.style.XSLCallTemplate
import net.sf.saxon.style.XSLCharacterMap
import net.sf.saxon.style.XSLChoose
import net.sf.saxon.style.XSLComment
import net.sf.saxon.style.XSLCopy
import net.sf.saxon.style.XSLCopyOf
import net.sf.saxon.style.XSLDecimalFormat
import net.sf.saxon.style.XSLDocument
import net.sf.saxon.style.XSLElement
import net.sf.saxon.style.XSLFallback
import net.sf.saxon.style.XSLForEach
import net.sf.saxon.style.XSLForEachGroup
import net.sf.saxon.style.XSLFunction
import net.sf.saxon.style.XSLGeneralIncorporate
import net.sf.saxon.style.XSLGeneralVariable
import net.sf.saxon.style.XSLIf
import net.sf.saxon.style.XSLImport
import net.sf.saxon.style.XSLImportSchema
import net.sf.saxon.style.XSLInclude
import net.sf.saxon.style.XSLKey
import net.sf.saxon.style.XSLMatchingSubstring
import net.sf.saxon.style.XSLMessage
import net.sf.saxon.style.XSLNamespace
import net.sf.saxon.style.XSLNamespaceAlias
import net.sf.saxon.style.XSLNextMatch
import net.sf.saxon.style.XSLNumber
import net.sf.saxon.style.XSLOtherwise
import net.sf.saxon.style.XSLOutput
import net.sf.saxon.style.XSLOutputCharacter
import net.sf.saxon.style.XSLParam
import net.sf.saxon.style.XSLPerformSort
import net.sf.saxon.style.XSLPreserveSpace
import net.sf.saxon.style.XSLProcessingInstruction
import net.sf.saxon.style.XSLResultDocument
import net.sf.saxon.style.XSLSequence
import net.sf.saxon.style.XSLSort
import net.sf.saxon.style.XSLStringConstructor
import net.sf.saxon.style.XSLStylesheet
import net.sf.saxon.style.XSLTemplate
import net.sf.saxon.style.XSLText
import net.sf.saxon.style.XSLTStaticContext
import net.sf.saxon.style.XSLValueOf
import net.sf.saxon.style.XSLVariable
import net.sf.saxon.style.XSLVariableDeclaration
import net.sf.saxon.style.XSLWhen
import net.sf.saxon.style.XSLWithParam
import net.sf.saxon.sxpath.AbstractStaticContext
import net.sf.saxon.sxpath.IndependentContext
import net.sf.saxon.sxpath.XPathDynamicContext
import net.sf.saxon.sxpath.XPathEvaluator
import net.sf.saxon.sxpath.XPathExpression
import net.sf.saxon.sxpath.XPathStaticContext
import net.sf.saxon.sxpath.XPathVariable
import net.sf.saxon.tinytree.AncestorEnumeration
import net.sf.saxon.tinytree.AttributeEnumeration
import net.sf.saxon.tinytree.CharSlice
import net.sf.saxon.tinytree.CompressedWhitespace
import net.sf.saxon.tinytree.DescendantEnumeration
import net.sf.saxon.tinytree.FollowingEnumeration
import net.sf.saxon.tinytree.LargeStringBuffer
import net.sf.saxon.tinytree.PrecedingEnumeration
import net.sf.saxon.tinytree.PrecedingSiblingEnumeration
import net.sf.saxon.tinytree.SiblingEnumeration
import net.sf.saxon.tinytree.TinyAttributeCollection
import net.sf.saxon.tinytree.TinyAttributeImpl
import net.sf.saxon.tinytree.TinyBuilder
import net.sf.saxon.tinytree.TinyCommentImpl
import net.sf.saxon.tinytree.TinyDocumentImpl
import net.sf.saxon.tinytree.TinyElementImpl
import net.sf.saxon.tinytree.TinyNodeImpl
import net.sf.saxon.tinytree.TinyParentNodeImpl
import net.sf.saxon.tinytree.TinyProcInstImpl
import net.sf.saxon.tinytree.TinyTextImpl
import net.sf.saxon.tinytree.TinyTree
import net.sf.saxon.tinytree.TinyTreeEventIterator
import net.sf.saxon.tinytree.TinyTreeWalker
import net.sf.saxon.tinytree.WhitespaceTextImpl
import net.sf.saxon.trace.AbstractTraceListener
import net.sf.saxon.trace.ContextStackFrame$ApplyTemplates
import net.sf.saxon.trace.ContextStackFrame$BuiltInTemplateRule
import net.sf.saxon.trace.ContextStackFrame$CallingApplication
import net.sf.saxon.trace.ContextStackFrame$CallTemplate
import net.sf.saxon.trace.ContextStackFrame$ForEach
import net.sf.saxon.trace.ContextStackFrame$FunctionCall
import net.sf.saxon.trace.ContextStackFrame$VariableEvaluation
import net.sf.saxon.trace.ContextStackFrame
import net.sf.saxon.trace.ContextStackIterator
import net.sf.saxon.trace.ExpressionPresenter
import net.sf.saxon.trace.InstructionInfo
import net.sf.saxon.trace.Location
import net.sf.saxon.trace.TimedTraceListener
import net.sf.saxon.trace.TraceEventMulticaster
import net.sf.saxon.trace.TraceListener
import net.sf.saxon.trace.XQueryTraceListener
import net.sf.saxon.trace.XSLTTraceListener
import net.sf.saxon.trans.CompilerInfo
import net.sf.saxon.trans.DecimalFormatManager$1
import net.sf.saxon.trans.DecimalFormatManager$DecimalFormatInfo
import net.sf.saxon.trans.DecimalFormatManager
import net.sf.saxon.trans.DecimalSymbols
import net.sf.saxon.trans.DynamicError
import net.sf.saxon.trans.DynamicLoader
import net.sf.saxon.trans.Err
import net.sf.saxon.trans.KeyDefinition
import net.sf.saxon.trans.KeyDefinitionSet
import net.sf.saxon.trans.KeyManager
import net.sf.saxon.trans.Mode
import net.sf.saxon.trans.NoDynamicContextException
import net.sf.saxon.trans.Rule
import net.sf.saxon.trans.RuleManager
import net.sf.saxon.trans.SaxonErrorCode
import net.sf.saxon.trans.StandardUnparsedTextResolver
import net.sf.saxon.trans.StaticError
import net.sf.saxon.trans.UncheckedXPathException
import net.sf.saxon.trans.UnparsedTextURIResolver
import net.sf.saxon.trans.XPathException$Circularity
import net.sf.saxon.trans.XPathException
import net.sf.saxon.tree.AncestorEnumeration
import net.sf.saxon.tree.AttributeEnumeration
import net.sf.saxon.tree.AttributeImpl
import net.sf.saxon.tree.ChildEnumeration
import net.sf.saxon.tree.CommentImpl
import net.sf.saxon.tree.DescendantEnumeration
import net.sf.saxon.tree.DocumentImpl
import net.sf.saxon.tree.ElementImpl$1
import net.sf.saxon.tree.ElementImpl
import net.sf.saxon.tree.FollowingEnumeration
import net.sf.saxon.tree.FollowingSiblingEnumeration
import net.sf.saxon.tree.LineNumberMap
import net.sf.saxon.tree.NodeFactory
import net.sf.saxon.tree.NodeImpl
import net.sf.saxon.tree.ParentNodeImpl
import net.sf.saxon.tree.PrecedingEnumeration
import net.sf.saxon.tree.PrecedingOrAncestorEnumeration
import net.sf.saxon.tree.PrecedingSiblingEnumeration
import net.sf.saxon.tree.ProcInstImpl
import net.sf.saxon.tree.SystemIdMap
import net.sf.saxon.tree.TextImpl
import net.sf.saxon.tree.TreeBuilder$1
import net.sf.saxon.tree.TreeBuilder$DefaultNodeFactory
import net.sf.saxon.tree.TreeBuilder
import net.sf.saxon.tree.TreeEnumeration
import net.sf.saxon.type.AnyItemType
import net.sf.saxon.type.AnySimpleType
import net.sf.saxon.type.AnyType
import net.sf.saxon.type.AtomicType
import net.sf.saxon.type.BuiltInAtomicType
import net.sf.saxon.type.BuiltInListType$1
import net.sf.saxon.type.BuiltInListType$ListTypeMappingFunction
import net.sf.saxon.type.BuiltInListType
import net.sf.saxon.type.BuiltInType
import net.sf.saxon.type.ComplexType
import net.sf.saxon.type.ConversionResult
import net.sf.saxon.type.ExternalObjectType
import net.sf.saxon.type.ISchemaCompiler
import net.sf.saxon.type.ItemType
import net.sf.saxon.type.ListType
import net.sf.saxon.type.SchemaComponent
import net.sf.saxon.type.SchemaDeclaration
import net.sf.saxon.type.SchemaException
import net.sf.saxon.type.SchemaType
import net.sf.saxon.type.SchemaURIResolver
import net.sf.saxon.type.SimpleType
import net.sf.saxon.type.Type
import net.sf.saxon.type.TypeHierarchy$ItemTypePair
import net.sf.saxon.type.TypeHierarchy
import net.sf.saxon.type.UnresolvedReferenceException
import net.sf.saxon.type.Untyped
import net.sf.saxon.type.ValidationException
import net.sf.saxon.type.ValidationFailure
import net.sf.saxon.value.AnyURIValue
import net.sf.saxon.value.AtomicValue
import net.sf.saxon.value.Base64BinaryValue$1
import net.sf.saxon.value.Base64BinaryValue$Base64BinaryComparable
import net.sf.saxon.value.Base64BinaryValue$Base64Decoder
import net.sf.saxon.value.Base64BinaryValue$Base64Encoder
import net.sf.saxon.value.Base64BinaryValue
import net.sf.saxon.value.BigIntegerValue$BigIntegerComparable
import net.sf.saxon.value.BigIntegerValue
import net.sf.saxon.value.BooleanValue$1
import net.sf.saxon.value.BooleanValue$BooleanComparable
import net.sf.saxon.value.BooleanValue
import net.sf.saxon.value.CalendarValue
import net.sf.saxon.value.Cardinality
import net.sf.saxon.value.Closure
import net.sf.saxon.value.DateTimeValue$1
import net.sf.saxon.value.DateTimeValue$DateTimeComparable
import net.sf.saxon.value.DateTimeValue
import net.sf.saxon.value.DateValue
import net.sf.saxon.value.DayTimeDurationValue
import net.sf.saxon.value.DecimalValue$DecimalComparable
import net.sf.saxon.value.DecimalValue
import net.sf.saxon.value.DoubleValue
import net.sf.saxon.value.DurationValue$DurationComparable
import net.sf.saxon.value.DurationValue
import net.sf.saxon.value.EmptySequence
import net.sf.saxon.value.FloatingPointConverter
import net.sf.saxon.value.FloatValue
import net.sf.saxon.value.GDateValue$1
import net.sf.saxon.value.GDateValue$GDateComparable
import net.sf.saxon.value.GDateValue
import net.sf.saxon.value.GDayValue
import net.sf.saxon.value.GMonthDayValue
import net.sf.saxon.value.GMonthValue
import net.sf.saxon.value.GYearMonthValue
import net.sf.saxon.value.GYearValue
import net.sf.saxon.value.HexBinaryValue$1
import net.sf.saxon.value.HexBinaryValue$HexBinaryComparable
import net.sf.saxon.value.HexBinaryValue
import net.sf.saxon.value.Int64Value$Int64Comparable
import net.sf.saxon.value.Int64Value
import net.sf.saxon.value.IntegerRange
import net.sf.saxon.value.IntegerValue
import net.sf.saxon.value.MemoClosure$ProgressiveIterator
import net.sf.saxon.value.MemoClosure
import net.sf.saxon.value.NotationValue$1
import net.sf.saxon.value.NotationValue$NotationComparable
import net.sf.saxon.value.NotationValue
import net.sf.saxon.value.NumericValue
import net.sf.saxon.value.ObjectValue
import net.sf.saxon.value.QNameValue$1
import net.sf.saxon.value.QNameValue$QNameComparable
import net.sf.saxon.value.QNameValue
import net.sf.saxon.value.QualifiedNameValue
import net.sf.saxon.value.SequenceExtent
import net.sf.saxon.value.SequenceType
import net.sf.saxon.value.ShareableSequence
import net.sf.saxon.value.SingletonClosure
import net.sf.saxon.value.SingletonNode
import net.sf.saxon.value.StringValue$CharacterIterator
import net.sf.saxon.value.StringValue
import net.sf.saxon.value.TextFragmentValue$1
import net.sf.saxon.value.TextFragmentValue$TextFragmentTextNode
import net.sf.saxon.value.TextFragmentValue
import net.sf.saxon.value.TimeValue$1
import net.sf.saxon.value.TimeValue$TimeComparable
import net.sf.saxon.value.TimeValue
import net.sf.saxon.value.UntypedAtomicValue
import net.sf.saxon.value.Value$1
import net.sf.saxon.value.Value$ValueSchemaComparable
import net.sf.saxon.value.Value
import net.sf.saxon.value.Whitespace
import net.sf.saxon.value.YearMonthDurationValue

def usedResponse = (param.responseId == null) ? response : responses.get(param.responseId)
def isJson = (usedResponse.body.bodyContentTypeEnum.toString() == 'json')

// Let's get our hands on the Task resource from the response. Since this Groovy rule is not trivial to write and
// maintain, we want to support both the read and the search use case with the same rule. The search use case assumes
// that there the response is a search Bundle containing exactly one Task resource.
def task = null
if (usedResponse.resource == "Task") {
    task = usedResponse.body.document
} else if (usedResponse.resource == "Bundle") {
    assert usedResponse.getFhirPathBoolean("Bundle.entry.where(resource is Task).count() = 1"): "Server didn't return a Bundle with a single Task."

    if (isJson) {
        for (entry in usedResponse.body.document.entry) {
            if (entry.resource.resourceType == "Task") {
                task = entry.resource
            }
        }
    } else {
        task = usedResponse.body.document.entry.'**'.find { it.name() == "Task" }
    }
}
assert task != null : "Couldn't extract Task resource from response."

// Now modify the Task status and write the result to the output. We also remove the narrative as there is no guarantee
// anymore that it still complies to the Task.
if (isJson) {
    task.status = param.newStatus
    if ("text" in task) {
        task.remove("text")
    }

    output[param.fixtureId] = JsonOutput.toJson(task)
} else {
    task.status.@value = param.newStatus
    if (task.text != null) {
        task.text.replaceNode {}
    }
    // The serializer in combination with the GPathResult (datatype of the XML Task) has the nasty habit of adding
    // "tag0" as the default namespace, so each FHIR element becomes "tag0:Task" etc. There are probably ways to solve
    // this in a decent way, but they are hard to find, so we just take a pragmatic approach and filter "tag0" from
    // the result.
    output[param.fixtureId] = XmlUtil.serialize(task).replace("tag0:", "").replace("xmlns:tag0", "xmlns")
}
