input.dir = src/Sandbox/MO-PoC
output.dir = output/R4/Sandbox/MO-PoC
informationStandard = Sandbox
goal = Test
usecase = MP9
serverAlias = nictiz

fhir.version = R4
packages = nictiz.fhir.nl.r4.medicationprocess9

loadresources.exclude = _reference
