input.dir = src/BgZ-MSZ-2-0/Prevalidation
output.dir = output/STU3/BgZ-MSZ-2-0/Prevalidation
informationStandard = BgZ MSZ 2.0.x
goal = Prevalidation
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.bgz
package.nictiz.fhir.nl.stu3.bgz = 2.0.3

targets.additional = \
    presetPatient/Retrieving-XIS-NoProvenance,\
    presetPatient/Serving-XIS-NoProvenance,\
    presetPatient/Serving-XIS-CheckContent,\
    customPatient/Serving-XIS-NoProvenance