input.dir = src/eOverdracht-4-0/Prevalidation
output.dir = output/STU3/eOverdracht/4.0/Prevalidation
informationStandard = eOverdracht 4.0
goal = Prevalidation
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.eoverdracht
package.nictiz.fhir.nl.stu3.eoverdracht = 4.0.0

components.dir = src/eOverdracht-4-0/_components
loadresources.exclude = _reference/resources/resources-specific
targets.additional = presetPatient/Sending-XIS-Nictiz-internal,presetPatient/Receiving-XIS-NoDocument, customPatient/Sending-XIS-Nictiz-internal
targets.adminOnly = presetPatient/Sending-XIS-Nictiz-internal, customPatient/Sending-XIS-Nictiz-internal
