input.dir = src/eOverdracht-4-2/Validation
output.dir = output/STU3/eOverdracht/4.2/Validation
informationStandard = eOverdracht 4.2
goal = Validation
serverAlias = nictiz

fhir.version = STU3
packages = nictiz.fhir.nl.stu3.eoverdracht
package.nictiz.fhir.nl.stu3.eoverdracht = 4.2.0-beta.2

components.dir = src/eOverdracht-4-2/_components
loadresources.exclude = _reference/resources/resources-specific
targets.additional = \
    PatientXXX_Zonnenberg/Sending-XIS-Nictiz-internal,\
    PatientXXX_Zonnenberg/Receiving-XIS-NoDocument,\
    PatientXXX_Zuidwijker/Sending-XIS-Nictiz-internal,\
    PatientXXX_Zuidwijker/Receiving-XIS-NoDocument,\
    PatientXXX_Zelst-Asaroglu/Sending-XIS-Nictiz-internal,\
    PatientXXX_Zelst-Asaroglu/Receiving-XIS-NoDocument,\
    PatientXXX-Aansluittest-B/Sending-XIS-Nictiz-internal,\
    PatientXXX-Aansluittest-B/Receiving-XIS-NoDocument,\
targets.adminOnly = \
    PatientXXX_Zonnenberg/Sending-XIS-Nictiz-internal,\
    PatientXXX_Zuidwijker/Sending-XIS-Nictiz-internal,\
    PatientXXX_Zelst-Asaroglu/Sending-XIS-Nictiz-internal,\
    PatientXXX-Aansluittest-B/Sending-XIS-Nictiz-internal