services:
  nts-in-docker:
    build: .
    image: nictiz-nts-in-docker
    container_name: nictiz-nts-in-docker
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ..
        target: /repo
        read_only: false
