services:
  nts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/Nictiz-testscript
    working_dir: /Nictiz-testscript
    tty: true

  single:
    # Builds a single NTS folder, like build-single.xml. To use:
    # > docker-compose run single src/path/to/NTS-folder/properties.xml
    extends:
      service: nts
    entrypoint: ant -f src/build-single.xml -propertyfile

  multiple:
    # Builds a set of NTS folders, like build-multiple.xml. To use:
    # > docker-compose run multiple -Dinput.dirs=src/path/to/first-NTS-folder,src/path/to/second-NTS-folder,etc
    extends:
      service: nts
    entrypoint: ant -f src/build-multiple.xml