input.dir = src/PatientCorrections-1-0/Cert
output.dir = output/R4/PatientCorrections-1-0/MedMij/Cert
informationStandard = Patient Corrections 1.x
usecase = MedMij
goal = Cert
serverAlias = nictizmedmij

fhir.version = R4
packages = nictiz.fhir.nl.r4.patientcorrections, nictiz.fhir.nl.r4.nl-core
package.nictiz.fhir.nl.r4.nl-core = 0.6.0-beta.2

targets.additional = XIS-Server-Nictiz-intern, PHR-Client-Nictiz-intern
targets.adminOnly = XIS-Server-Nictiz-intern, PHR-Client-Nictiz-intern
Nictiz-intern.comment = Target Nicitz-intern exists because the Conformancelab FHIR Server does not send the OperationOutcome in the response Bundle as the standard specifies, see CL-363

loadresources.exclude = _reference/resources-specific